# Generated by Django 3.1.1 on 2020-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
