# Generated by Django 3.1.1 on 2020-09-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pruducts',
            new_name='products',
        ),
    ]
