# Generated by Django 3.1.1 on 2020-12-18 07:00

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='//dung-ecommerce.s3.us-east-2.amazonaws.com/media/'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
