# Generated by Django 3.1.1 on 2020-12-18 07:23

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201218_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='protected_media/'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
